// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tbadmin/shop.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Rising_Thunder_Server_CS.Protobufs.Tbadmin {

  /// <summary>Holder for reflection information generated from tbadmin/shop.proto</summary>
  public static partial class ShopReflection {

    #region Descriptor
    /// <summary>File descriptor for tbadmin/shop.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ShopReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJ0YmFkbWluL3Nob3AucHJvdG8SB3RiYWRtaW4aEXRicnBjL3RicnBjLnBy",
            "b3RvGhJ0Ym1hdGNoL3Nob3AucHJvdG8aE3RibWF0Y2gvcXVlcnkucHJvdG8i",
            "/QIKDU9yZGVyQ3JpdGVyaWESEgoKYWNjb3VudF9pZBgBIAEoAxIqCgxvcmRl",
            "cl9zdGF0dXMYAiABKA4yFC50Ym1hdGNoLk9yZGVyU3RhdHVzEicKC21vZGlm",
            "eV90aW1lGAMgASgLMhIudGJtYXRjaC5UaW1lUmFuZ2USJgoQbWluX3RvdGFs",
            "X2Ftb3VudBgFIAEoCzIMLnRicnBjLk1vbmV5EiYKEG1heF90b3RhbF9hbW91",
            "bnQYBiABKAsyDC50YnJwYy5Nb25leRIbChN1c2VfYWNjb3VudF9iYWxhbmNl",
            "GAogASgIEiwKDmJpbGxfbGFzdF9uYW1lGAsgASgLMhQudGJtYXRjaC5TdHJp",
            "bmdNYXRjaBInCgliaWxsX2NpdHkYDCABKAsyFC50Ym1hdGNoLlN0cmluZ01h",
            "dGNoEikKC2JpbGxfcmVnaW9uGA0gASgLMhQudGJtYXRjaC5TdHJpbmdNYXRj",
            "aBIUCgxiaWxsX2NvdW50cnkYDiABKAkiiAEKG1NlYXJjaFB1cmNoYXNlT3Jk",
            "ZXJzUmVxdWVzdBIoCghjcml0ZXJpYRgBIAEoCzIWLnRiYWRtaW4uT3JkZXJD",
            "cml0ZXJpYRIgCgRzb3J0GAIgASgLMhIudGJtYXRjaC5PcmRlclNvcnQSDgoG",
            "b2Zmc2V0GAUgASgFEg0KBWxpbWl0GAYgASgFIlkKGlNlYXJjaFB1cmNoYXNl",
            "T3JkZXJzUmVzdWx0EiYKBm9yZGVycxgBIAMoCzIWLnRibWF0Y2guUHVyY2hh",
            "c2VPcmRlchITCgtlbmRfb2ZfZGF0YRgCIAEoCCIwChhTeW5jUHVyY2hhc2VP",
            "cmRlclJlcXVlc3QSFAoMb3JkZXJfbnVtYmVyGAEgASgDIjAKGFZvaWRQdXJj",
            "aGFzZU9yZGVyUmVxdWVzdBIUCgxvcmRlcl9udW1iZXIYASABKAMiMgoaUmVm",
            "dW5kUHVyY2hhc2VPcmRlclJlcXVlc3QSFAoMb3JkZXJfbnVtYmVyGAEgASgD",
            "MuMCChBTaG9wQWRtaW5TZXJ2aWNlEmcKFFNlYXJjaFB1cmNoYXNlT3JkZXJz",
            "EiQudGJhZG1pbi5TZWFyY2hQdXJjaGFzZU9yZGVyc1JlcXVlc3QaIy50YmFk",
            "bWluLlNlYXJjaFB1cmNoYXNlT3JkZXJzUmVzdWx0IgTI8xgWEkoKEVN5bmNQ",
            "dXJjaGFzZU9yZGVyEiEudGJhZG1pbi5TeW5jUHVyY2hhc2VPcmRlclJlcXVl",
            "c3QaDC50YnJwYy5FbXB0eSIEyPMYFhJKChFWb2lkUHVyY2hhc2VPcmRlchIh",
            "LnRiYWRtaW4uVm9pZFB1cmNoYXNlT3JkZXJSZXF1ZXN0GgwudGJycGMuRW1w",
            "dHkiBMjzGBcSTgoTUmVmdW5kUHVyY2hhc2VPcmRlchIjLnRiYWRtaW4uUmVm",
            "dW5kUHVyY2hhc2VPcmRlclJlcXVlc3QaDC50YnJwYy5FbXB0eSIEyPMYF2IG",
            "cHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Rising_Thunder_Server_CS.Protobufs.Tbrpc.TbrpcReflection.Descriptor, global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.ShopReflection.Descriptor, global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.QueryReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.OrderCriteria), global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.OrderCriteria.Parser, new[]{ "AccountId", "OrderStatus", "ModifyTime", "MinTotalAmount", "MaxTotalAmount", "UseAccountBalance", "BillLastName", "BillCity", "BillRegion", "BillCountry" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.SearchPurchaseOrdersRequest), global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.SearchPurchaseOrdersRequest.Parser, new[]{ "Criteria", "Sort", "Offset", "Limit" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.SearchPurchaseOrdersResult), global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.SearchPurchaseOrdersResult.Parser, new[]{ "Orders", "EndOfData" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.SyncPurchaseOrderRequest), global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.SyncPurchaseOrderRequest.Parser, new[]{ "OrderNumber" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.VoidPurchaseOrderRequest), global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.VoidPurchaseOrderRequest.Parser, new[]{ "OrderNumber" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.RefundPurchaseOrderRequest), global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.RefundPurchaseOrderRequest.Parser, new[]{ "OrderNumber" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// restrictions for an order search.
  /// </summary>
  public sealed partial class OrderCriteria : pb::IMessage<OrderCriteria> {
    private static readonly pb::MessageParser<OrderCriteria> _parser = new pb::MessageParser<OrderCriteria>(() => new OrderCriteria());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OrderCriteria> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.ShopReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderCriteria() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderCriteria(OrderCriteria other) : this() {
      accountId_ = other.accountId_;
      orderStatus_ = other.orderStatus_;
      ModifyTime = other.modifyTime_ != null ? other.ModifyTime.Clone() : null;
      MinTotalAmount = other.minTotalAmount_ != null ? other.MinTotalAmount.Clone() : null;
      MaxTotalAmount = other.maxTotalAmount_ != null ? other.MaxTotalAmount.Clone() : null;
      useAccountBalance_ = other.useAccountBalance_;
      BillLastName = other.billLastName_ != null ? other.BillLastName.Clone() : null;
      BillCity = other.billCity_ != null ? other.BillCity.Clone() : null;
      BillRegion = other.billRegion_ != null ? other.BillRegion.Clone() : null;
      billCountry_ = other.billCountry_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OrderCriteria Clone() {
      return new OrderCriteria(this);
    }

    /// <summary>Field number for the "account_id" field.</summary>
    public const int AccountIdFieldNumber = 1;
    private long accountId_;
    /// <summary>
    /// If set, restrict by owning account.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long AccountId {
      get { return accountId_; }
      set {
        accountId_ = value;
      }
    }

    /// <summary>Field number for the "order_status" field.</summary>
    public const int OrderStatusFieldNumber = 2;
    private global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.OrderStatus orderStatus_ = 0;
    /// <summary>
    /// If set, restrict by specific order status.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.OrderStatus OrderStatus {
      get { return orderStatus_; }
      set {
        orderStatus_ = value;
      }
    }

    /// <summary>Field number for the "modify_time" field.</summary>
    public const int ModifyTimeFieldNumber = 3;
    private global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.TimeRange modifyTime_;
    /// <summary>
    /// Restrict time range for last modify time.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.TimeRange ModifyTime {
      get { return modifyTime_; }
      set {
        modifyTime_ = value;
      }
    }

    /// <summary>Field number for the "min_total_amount" field.</summary>
    public const int MinTotalAmountFieldNumber = 5;
    private global::Rising_Thunder_Server_CS.Protobufs.Tbrpc.Money minTotalAmount_;
    /// <summary>
    /// Total amount range.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rising_Thunder_Server_CS.Protobufs.Tbrpc.Money MinTotalAmount {
      get { return minTotalAmount_; }
      set {
        minTotalAmount_ = value;
      }
    }

    /// <summary>Field number for the "max_total_amount" field.</summary>
    public const int MaxTotalAmountFieldNumber = 6;
    private global::Rising_Thunder_Server_CS.Protobufs.Tbrpc.Money maxTotalAmount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rising_Thunder_Server_CS.Protobufs.Tbrpc.Money MaxTotalAmount {
      get { return maxTotalAmount_; }
      set {
        maxTotalAmount_ = value;
      }
    }

    /// <summary>Field number for the "use_account_balance" field.</summary>
    public const int UseAccountBalanceFieldNumber = 10;
    private bool useAccountBalance_;
    /// <summary>
    /// If set, orders that use account balance (or not).
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool UseAccountBalance {
      get { return useAccountBalance_; }
      set {
        useAccountBalance_ = value;
      }
    }

    /// <summary>Field number for the "bill_last_name" field.</summary>
    public const int BillLastNameFieldNumber = 11;
    private global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch billLastName_;
    /// <summary>
    /// Match billing fields.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch BillLastName {
      get { return billLastName_; }
      set {
        billLastName_ = value;
      }
    }

    /// <summary>Field number for the "bill_city" field.</summary>
    public const int BillCityFieldNumber = 12;
    private global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch billCity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch BillCity {
      get { return billCity_; }
      set {
        billCity_ = value;
      }
    }

    /// <summary>Field number for the "bill_region" field.</summary>
    public const int BillRegionFieldNumber = 13;
    private global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch billRegion_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch BillRegion {
      get { return billRegion_; }
      set {
        billRegion_ = value;
      }
    }

    /// <summary>Field number for the "bill_country" field.</summary>
    public const int BillCountryFieldNumber = 14;
    private string billCountry_ = "";
    /// <summary>
    /// Limit to country.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string BillCountry {
      get { return billCountry_; }
      set {
        billCountry_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OrderCriteria);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OrderCriteria other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (AccountId != other.AccountId) return false;
      if (OrderStatus != other.OrderStatus) return false;
      if (!object.Equals(ModifyTime, other.ModifyTime)) return false;
      if (!object.Equals(MinTotalAmount, other.MinTotalAmount)) return false;
      if (!object.Equals(MaxTotalAmount, other.MaxTotalAmount)) return false;
      if (UseAccountBalance != other.UseAccountBalance) return false;
      if (!object.Equals(BillLastName, other.BillLastName)) return false;
      if (!object.Equals(BillCity, other.BillCity)) return false;
      if (!object.Equals(BillRegion, other.BillRegion)) return false;
      if (BillCountry != other.BillCountry) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (AccountId != 0L) hash ^= AccountId.GetHashCode();
      if (OrderStatus != 0) hash ^= OrderStatus.GetHashCode();
      if (modifyTime_ != null) hash ^= ModifyTime.GetHashCode();
      if (minTotalAmount_ != null) hash ^= MinTotalAmount.GetHashCode();
      if (maxTotalAmount_ != null) hash ^= MaxTotalAmount.GetHashCode();
      if (UseAccountBalance != false) hash ^= UseAccountBalance.GetHashCode();
      if (billLastName_ != null) hash ^= BillLastName.GetHashCode();
      if (billCity_ != null) hash ^= BillCity.GetHashCode();
      if (billRegion_ != null) hash ^= BillRegion.GetHashCode();
      if (BillCountry.Length != 0) hash ^= BillCountry.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (AccountId != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(AccountId);
      }
      if (OrderStatus != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) OrderStatus);
      }
      if (modifyTime_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(ModifyTime);
      }
      if (minTotalAmount_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(MinTotalAmount);
      }
      if (maxTotalAmount_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(MaxTotalAmount);
      }
      if (UseAccountBalance != false) {
        output.WriteRawTag(80);
        output.WriteBool(UseAccountBalance);
      }
      if (billLastName_ != null) {
        output.WriteRawTag(90);
        output.WriteMessage(BillLastName);
      }
      if (billCity_ != null) {
        output.WriteRawTag(98);
        output.WriteMessage(BillCity);
      }
      if (billRegion_ != null) {
        output.WriteRawTag(106);
        output.WriteMessage(BillRegion);
      }
      if (BillCountry.Length != 0) {
        output.WriteRawTag(114);
        output.WriteString(BillCountry);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (AccountId != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(AccountId);
      }
      if (OrderStatus != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OrderStatus);
      }
      if (modifyTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ModifyTime);
      }
      if (minTotalAmount_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MinTotalAmount);
      }
      if (maxTotalAmount_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(MaxTotalAmount);
      }
      if (UseAccountBalance != false) {
        size += 1 + 1;
      }
      if (billLastName_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BillLastName);
      }
      if (billCity_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BillCity);
      }
      if (billRegion_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BillRegion);
      }
      if (BillCountry.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(BillCountry);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OrderCriteria other) {
      if (other == null) {
        return;
      }
      if (other.AccountId != 0L) {
        AccountId = other.AccountId;
      }
      if (other.OrderStatus != 0) {
        OrderStatus = other.OrderStatus;
      }
      if (other.modifyTime_ != null) {
        if (modifyTime_ == null) {
          modifyTime_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.TimeRange();
        }
        ModifyTime.MergeFrom(other.ModifyTime);
      }
      if (other.minTotalAmount_ != null) {
        if (minTotalAmount_ == null) {
          minTotalAmount_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbrpc.Money();
        }
        MinTotalAmount.MergeFrom(other.MinTotalAmount);
      }
      if (other.maxTotalAmount_ != null) {
        if (maxTotalAmount_ == null) {
          maxTotalAmount_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbrpc.Money();
        }
        MaxTotalAmount.MergeFrom(other.MaxTotalAmount);
      }
      if (other.UseAccountBalance != false) {
        UseAccountBalance = other.UseAccountBalance;
      }
      if (other.billLastName_ != null) {
        if (billLastName_ == null) {
          billLastName_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch();
        }
        BillLastName.MergeFrom(other.BillLastName);
      }
      if (other.billCity_ != null) {
        if (billCity_ == null) {
          billCity_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch();
        }
        BillCity.MergeFrom(other.BillCity);
      }
      if (other.billRegion_ != null) {
        if (billRegion_ == null) {
          billRegion_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch();
        }
        BillRegion.MergeFrom(other.BillRegion);
      }
      if (other.BillCountry.Length != 0) {
        BillCountry = other.BillCountry;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            AccountId = input.ReadInt64();
            break;
          }
          case 16: {
            orderStatus_ = (global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.OrderStatus) input.ReadEnum();
            break;
          }
          case 26: {
            if (modifyTime_ == null) {
              modifyTime_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.TimeRange();
            }
            input.ReadMessage(modifyTime_);
            break;
          }
          case 42: {
            if (minTotalAmount_ == null) {
              minTotalAmount_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbrpc.Money();
            }
            input.ReadMessage(minTotalAmount_);
            break;
          }
          case 50: {
            if (maxTotalAmount_ == null) {
              maxTotalAmount_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbrpc.Money();
            }
            input.ReadMessage(maxTotalAmount_);
            break;
          }
          case 80: {
            UseAccountBalance = input.ReadBool();
            break;
          }
          case 90: {
            if (billLastName_ == null) {
              billLastName_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch();
            }
            input.ReadMessage(billLastName_);
            break;
          }
          case 98: {
            if (billCity_ == null) {
              billCity_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch();
            }
            input.ReadMessage(billCity_);
            break;
          }
          case 106: {
            if (billRegion_ == null) {
              billRegion_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.StringMatch();
            }
            input.ReadMessage(billRegion_);
            break;
          }
          case 114: {
            BillCountry = input.ReadString();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Search for purchase orders.
  /// </summary>
  public sealed partial class SearchPurchaseOrdersRequest : pb::IMessage<SearchPurchaseOrdersRequest> {
    private static readonly pb::MessageParser<SearchPurchaseOrdersRequest> _parser = new pb::MessageParser<SearchPurchaseOrdersRequest>(() => new SearchPurchaseOrdersRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SearchPurchaseOrdersRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.ShopReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SearchPurchaseOrdersRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SearchPurchaseOrdersRequest(SearchPurchaseOrdersRequest other) : this() {
      Criteria = other.criteria_ != null ? other.Criteria.Clone() : null;
      Sort = other.sort_ != null ? other.Sort.Clone() : null;
      offset_ = other.offset_;
      limit_ = other.limit_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SearchPurchaseOrdersRequest Clone() {
      return new SearchPurchaseOrdersRequest(this);
    }

    /// <summary>Field number for the "criteria" field.</summary>
    public const int CriteriaFieldNumber = 1;
    private global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.OrderCriteria criteria_;
    /// <summary>
    /// Restrictions on the search.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.OrderCriteria Criteria {
      get { return criteria_; }
      set {
        criteria_ = value;
      }
    }

    /// <summary>Field number for the "sort" field.</summary>
    public const int SortFieldNumber = 2;
    private global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.OrderSort sort_;
    /// <summary>
    /// Order sorting
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.OrderSort Sort {
      get { return sort_; }
      set {
        sort_ = value;
      }
    }

    /// <summary>Field number for the "offset" field.</summary>
    public const int OffsetFieldNumber = 5;
    private int offset_;
    /// <summary>
    /// Skip past this many records in the result.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Offset {
      get { return offset_; }
      set {
        offset_ = value;
      }
    }

    /// <summary>Field number for the "limit" field.</summary>
    public const int LimitFieldNumber = 6;
    private int limit_;
    /// <summary>
    /// Max number of results to return.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int Limit {
      get { return limit_; }
      set {
        limit_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SearchPurchaseOrdersRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SearchPurchaseOrdersRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(Criteria, other.Criteria)) return false;
      if (!object.Equals(Sort, other.Sort)) return false;
      if (Offset != other.Offset) return false;
      if (Limit != other.Limit) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (criteria_ != null) hash ^= Criteria.GetHashCode();
      if (sort_ != null) hash ^= Sort.GetHashCode();
      if (Offset != 0) hash ^= Offset.GetHashCode();
      if (Limit != 0) hash ^= Limit.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (criteria_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Criteria);
      }
      if (sort_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(Sort);
      }
      if (Offset != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(Offset);
      }
      if (Limit != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(Limit);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (criteria_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Criteria);
      }
      if (sort_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Sort);
      }
      if (Offset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Offset);
      }
      if (Limit != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(Limit);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SearchPurchaseOrdersRequest other) {
      if (other == null) {
        return;
      }
      if (other.criteria_ != null) {
        if (criteria_ == null) {
          criteria_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.OrderCriteria();
        }
        Criteria.MergeFrom(other.Criteria);
      }
      if (other.sort_ != null) {
        if (sort_ == null) {
          sort_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.OrderSort();
        }
        Sort.MergeFrom(other.Sort);
      }
      if (other.Offset != 0) {
        Offset = other.Offset;
      }
      if (other.Limit != 0) {
        Limit = other.Limit;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (criteria_ == null) {
              criteria_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.OrderCriteria();
            }
            input.ReadMessage(criteria_);
            break;
          }
          case 18: {
            if (sort_ == null) {
              sort_ = new global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.OrderSort();
            }
            input.ReadMessage(sort_);
            break;
          }
          case 40: {
            Offset = input.ReadInt32();
            break;
          }
          case 48: {
            Limit = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class SearchPurchaseOrdersResult : pb::IMessage<SearchPurchaseOrdersResult> {
    private static readonly pb::MessageParser<SearchPurchaseOrdersResult> _parser = new pb::MessageParser<SearchPurchaseOrdersResult>(() => new SearchPurchaseOrdersResult());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SearchPurchaseOrdersResult> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.ShopReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SearchPurchaseOrdersResult() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SearchPurchaseOrdersResult(SearchPurchaseOrdersResult other) : this() {
      orders_ = other.orders_.Clone();
      endOfData_ = other.endOfData_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SearchPurchaseOrdersResult Clone() {
      return new SearchPurchaseOrdersResult(this);
    }

    /// <summary>Field number for the "orders" field.</summary>
    public const int OrdersFieldNumber = 1;
    private static readonly pb::FieldCodec<global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.PurchaseOrder> _repeated_orders_codec
        = pb::FieldCodec.ForMessage(10, global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.PurchaseOrder.Parser);
    private readonly pbc::RepeatedField<global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.PurchaseOrder> orders_ = new pbc::RepeatedField<global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.PurchaseOrder>();
    /// <summary>
    /// Orders that matched the criteria.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Rising_Thunder_Server_CS.Protobufs.Tbmatch.PurchaseOrder> Orders {
      get { return orders_; }
    }

    /// <summary>Field number for the "end_of_data" field.</summary>
    public const int EndOfDataFieldNumber = 2;
    private bool endOfData_;
    /// <summary>
    /// True when the included results reached the end of the query result.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool EndOfData {
      get { return endOfData_; }
      set {
        endOfData_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SearchPurchaseOrdersResult);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SearchPurchaseOrdersResult other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!orders_.Equals(other.orders_)) return false;
      if (EndOfData != other.EndOfData) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= orders_.GetHashCode();
      if (EndOfData != false) hash ^= EndOfData.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      orders_.WriteTo(output, _repeated_orders_codec);
      if (EndOfData != false) {
        output.WriteRawTag(16);
        output.WriteBool(EndOfData);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += orders_.CalculateSize(_repeated_orders_codec);
      if (EndOfData != false) {
        size += 1 + 1;
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SearchPurchaseOrdersResult other) {
      if (other == null) {
        return;
      }
      orders_.Add(other.orders_);
      if (other.EndOfData != false) {
        EndOfData = other.EndOfData;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            orders_.AddEntriesFrom(input, _repeated_orders_codec);
            break;
          }
          case 16: {
            EndOfData = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Reconcile a purchase order state with external
  /// payment processing transaction state.
  /// </summary>
  public sealed partial class SyncPurchaseOrderRequest : pb::IMessage<SyncPurchaseOrderRequest> {
    private static readonly pb::MessageParser<SyncPurchaseOrderRequest> _parser = new pb::MessageParser<SyncPurchaseOrderRequest>(() => new SyncPurchaseOrderRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<SyncPurchaseOrderRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.ShopReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncPurchaseOrderRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncPurchaseOrderRequest(SyncPurchaseOrderRequest other) : this() {
      orderNumber_ = other.orderNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public SyncPurchaseOrderRequest Clone() {
      return new SyncPurchaseOrderRequest(this);
    }

    /// <summary>Field number for the "order_number" field.</summary>
    public const int OrderNumberFieldNumber = 1;
    private long orderNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OrderNumber {
      get { return orderNumber_; }
      set {
        orderNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as SyncPurchaseOrderRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(SyncPurchaseOrderRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderNumber != other.OrderNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderNumber != 0L) hash ^= OrderNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OrderNumber != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(OrderNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OrderNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OrderNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(SyncPurchaseOrderRequest other) {
      if (other == null) {
        return;
      }
      if (other.OrderNumber != 0L) {
        OrderNumber = other.OrderNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderNumber = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Cancel a pending purchase order.
  /// </summary>
  public sealed partial class VoidPurchaseOrderRequest : pb::IMessage<VoidPurchaseOrderRequest> {
    private static readonly pb::MessageParser<VoidPurchaseOrderRequest> _parser = new pb::MessageParser<VoidPurchaseOrderRequest>(() => new VoidPurchaseOrderRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<VoidPurchaseOrderRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.ShopReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VoidPurchaseOrderRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VoidPurchaseOrderRequest(VoidPurchaseOrderRequest other) : this() {
      orderNumber_ = other.orderNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public VoidPurchaseOrderRequest Clone() {
      return new VoidPurchaseOrderRequest(this);
    }

    /// <summary>Field number for the "order_number" field.</summary>
    public const int OrderNumberFieldNumber = 1;
    private long orderNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OrderNumber {
      get { return orderNumber_; }
      set {
        orderNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as VoidPurchaseOrderRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(VoidPurchaseOrderRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderNumber != other.OrderNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderNumber != 0L) hash ^= OrderNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OrderNumber != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(OrderNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OrderNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OrderNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(VoidPurchaseOrderRequest other) {
      if (other == null) {
        return;
      }
      if (other.OrderNumber != 0L) {
        OrderNumber = other.OrderNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderNumber = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// Refund a completed purchase order with settled payment.
  /// </summary>
  public sealed partial class RefundPurchaseOrderRequest : pb::IMessage<RefundPurchaseOrderRequest> {
    private static readonly pb::MessageParser<RefundPurchaseOrderRequest> _parser = new pb::MessageParser<RefundPurchaseOrderRequest>(() => new RefundPurchaseOrderRequest());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RefundPurchaseOrderRequest> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Rising_Thunder_Server_CS.Protobufs.Tbadmin.ShopReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefundPurchaseOrderRequest() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefundPurchaseOrderRequest(RefundPurchaseOrderRequest other) : this() {
      orderNumber_ = other.orderNumber_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RefundPurchaseOrderRequest Clone() {
      return new RefundPurchaseOrderRequest(this);
    }

    /// <summary>Field number for the "order_number" field.</summary>
    public const int OrderNumberFieldNumber = 1;
    private long orderNumber_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long OrderNumber {
      get { return orderNumber_; }
      set {
        orderNumber_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RefundPurchaseOrderRequest);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RefundPurchaseOrderRequest other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (OrderNumber != other.OrderNumber) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (OrderNumber != 0L) hash ^= OrderNumber.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (OrderNumber != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(OrderNumber);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (OrderNumber != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(OrderNumber);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RefundPurchaseOrderRequest other) {
      if (other == null) {
        return;
      }
      if (other.OrderNumber != 0L) {
        OrderNumber = other.OrderNumber;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            OrderNumber = input.ReadInt64();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
