// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: tbmatch/log.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Tbmatch {

  /// <summary>Holder for reflection information generated from tbmatch/log.proto</summary>
  public static partial class LogReflection {

    #region Descriptor
    /// <summary>File descriptor for tbmatch/log.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static LogReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChF0Ym1hdGNoL2xvZy5wcm90bxIHdGJtYXRjaCK7AgoKTG9nTWVzc2FnZRIW",
            "Cg50aW1lc3RhbXBfbXNlYxgBIAEoAxIPCgdtZXNzYWdlGAIgASgJEi4KCHBy",
            "aW9yaXR5GAMgASgOMhwudGJtYXRjaC5Mb2dNZXNzYWdlLlByaW9yaXR5EioK",
            "BnNvdXJjZRgEIAEoCzIaLnRibWF0Y2guTG9nTWVzc2FnZS5Tb3VyY2UaLgoG",
            "U291cmNlEhMKC2FwcGxpY2F0aW9uGAEgASgJEg8KB2FkZHJlc3MYAiABKAki",
            "LQoKRW50aXR5VHlwZRIUChBFTlRJVFlfVFlQRV9aRVJPEAASCQoFTUFUQ0gQ",
            "ASJJCghQcmlvcml0eRIRCg1QUklPUklUWV9aRVJPEAASCQoFRkFUQUwQARIJ",
            "CgVFUlJPUhACEggKBElORk8QAxIKCgZUUklWSUEQBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Tbmatch.LogMessage), global::Tbmatch.LogMessage.Parser, new[]{ "TimestampMsec", "Message", "Priority", "Source" }, null, new[]{ typeof(global::Tbmatch.LogMessage.Types.EntityType), typeof(global::Tbmatch.LogMessage.Types.Priority) }, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Tbmatch.LogMessage.Types.Source), global::Tbmatch.LogMessage.Types.Source.Parser, new[]{ "Application", "Address" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// This represents a single log message generated by an application pertaining to some entity.
  ///   e.g.: One log message from Portal for a given Match.
  /// </summary>
  public sealed partial class LogMessage : pb::IMessage<LogMessage> {
    private static readonly pb::MessageParser<LogMessage> _parser = new pb::MessageParser<LogMessage>(() => new LogMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<LogMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Tbmatch.LogReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LogMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LogMessage(LogMessage other) : this() {
      timestampMsec_ = other.timestampMsec_;
      message_ = other.message_;
      priority_ = other.priority_;
      Source = other.source_ != null ? other.Source.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public LogMessage Clone() {
      return new LogMessage(this);
    }

    /// <summary>Field number for the "timestamp_msec" field.</summary>
    public const int TimestampMsecFieldNumber = 1;
    private long timestampMsec_;
    /// <summary>
    /// The timestamp at which this message was generated.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long TimestampMsec {
      get { return timestampMsec_; }
      set {
        timestampMsec_ = value;
      }
    }

    /// <summary>Field number for the "message" field.</summary>
    public const int MessageFieldNumber = 2;
    private string message_ = "";
    /// <summary>
    /// The log or debug message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Message {
      get { return message_; }
      set {
        message_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "priority" field.</summary>
    public const int PriorityFieldNumber = 3;
    private global::Tbmatch.LogMessage.Types.Priority priority_ = 0;
    /// <summary>
    /// The log level of the message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tbmatch.LogMessage.Types.Priority Priority {
      get { return priority_; }
      set {
        priority_ = value;
      }
    }

    /// <summary>Field number for the "source" field.</summary>
    public const int SourceFieldNumber = 4;
    private global::Tbmatch.LogMessage.Types.Source source_;
    /// <summary>
    /// The source of the log message.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Tbmatch.LogMessage.Types.Source Source {
      get { return source_; }
      set {
        source_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as LogMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(LogMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TimestampMsec != other.TimestampMsec) return false;
      if (Message != other.Message) return false;
      if (Priority != other.Priority) return false;
      if (!object.Equals(Source, other.Source)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (TimestampMsec != 0L) hash ^= TimestampMsec.GetHashCode();
      if (Message.Length != 0) hash ^= Message.GetHashCode();
      if (Priority != 0) hash ^= Priority.GetHashCode();
      if (source_ != null) hash ^= Source.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (TimestampMsec != 0L) {
        output.WriteRawTag(8);
        output.WriteInt64(TimestampMsec);
      }
      if (Message.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Message);
      }
      if (Priority != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Priority);
      }
      if (source_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(Source);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (TimestampMsec != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TimestampMsec);
      }
      if (Message.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Message);
      }
      if (Priority != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Priority);
      }
      if (source_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Source);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(LogMessage other) {
      if (other == null) {
        return;
      }
      if (other.TimestampMsec != 0L) {
        TimestampMsec = other.TimestampMsec;
      }
      if (other.Message.Length != 0) {
        Message = other.Message;
      }
      if (other.Priority != 0) {
        Priority = other.Priority;
      }
      if (other.source_ != null) {
        if (source_ == null) {
          source_ = new global::Tbmatch.LogMessage.Types.Source();
        }
        Source.MergeFrom(other.Source);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            TimestampMsec = input.ReadInt64();
            break;
          }
          case 18: {
            Message = input.ReadString();
            break;
          }
          case 24: {
            priority_ = (global::Tbmatch.LogMessage.Types.Priority) input.ReadEnum();
            break;
          }
          case 34: {
            if (source_ == null) {
              source_ = new global::Tbmatch.LogMessage.Types.Source();
            }
            input.ReadMessage(source_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the LogMessage message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      /// <summary>
      /// The type of entity to which the log message pertains
      /// </summary>
      public enum EntityType {
        [pbr::OriginalName("ENTITY_TYPE_ZERO")] Zero = 0,
        /// <summary>
        /// An online match
        /// </summary>
        [pbr::OriginalName("MATCH")] Match = 1,
      }

      /// <summary>
      /// The various possible log levels
      /// </summary>
      public enum Priority {
        [pbr::OriginalName("PRIORITY_ZERO")] Zero = 0,
        /// <summary>
        /// The application will probably terminate after this message is logged.
        /// </summary>
        [pbr::OriginalName("FATAL")] Fatal = 1,
        /// <summary>
        /// An error was encountered, but the application will resume.
        /// </summary>
        [pbr::OriginalName("ERROR")] Error = 2,
        /// <summary>
        /// Something unexpected or noteworthy occurred that didn't break anything.
        /// </summary>
        [pbr::OriginalName("INFO")] Info = 3,
        /// <summary>
        /// Verbose log entries, debug information, etc.
        /// </summary>
        [pbr::OriginalName("TRIVIA")] Trivia = 4,
      }

      /// <summary>
      /// Information about the originator of the log message
      /// </summary>
      public sealed partial class Source : pb::IMessage<Source> {
        private static readonly pb::MessageParser<Source> _parser = new pb::MessageParser<Source>(() => new Source());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Source> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Tbmatch.LogMessage.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Source() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Source(Source other) : this() {
          application_ = other.application_;
          address_ = other.address_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Source Clone() {
          return new Source(this);
        }

        /// <summary>Field number for the "application" field.</summary>
        public const int ApplicationFieldNumber = 1;
        private string application_ = "";
        /// <summary>
        /// The name of the application that generated the message.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Application {
          get { return application_; }
          set {
            application_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        /// <summary>Field number for the "address" field.</summary>
        public const int AddressFieldNumber = 2;
        private string address_ = "";
        /// <summary>
        /// The IP address or hostname of the machine from which the message originated.
        /// </summary>
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public string Address {
          get { return address_; }
          set {
            address_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Source);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Source other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Application != other.Application) return false;
          if (Address != other.Address) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Application.Length != 0) hash ^= Application.GetHashCode();
          if (Address.Length != 0) hash ^= Address.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Application.Length != 0) {
            output.WriteRawTag(10);
            output.WriteString(Application);
          }
          if (Address.Length != 0) {
            output.WriteRawTag(18);
            output.WriteString(Address);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Application.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Application);
          }
          if (Address.Length != 0) {
            size += 1 + pb::CodedOutputStream.ComputeStringSize(Address);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Source other) {
          if (other == null) {
            return;
          }
          if (other.Application.Length != 0) {
            Application = other.Application;
          }
          if (other.Address.Length != 0) {
            Address = other.Address;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 10: {
                Application = input.ReadString();
                break;
              }
              case 18: {
                Address = input.ReadString();
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
